apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/avdockerid/leaf:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/avdockerid/leaf:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: leaf
        chartPath: charts/leaf
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/avdockerid/leaf'
          image.tag: '{{.DIGEST_HEX}}'
