name: PR

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  send-team-notification:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:     
     - name: Pull Request
       uses: aliencube/microsoft-teams-actions@v0.8.0
       with:
          webhook_uri: https://outlook.office.com/webhook/90839495-dd23-4205-853a-6c78911c0803@af16bf88-a652-447e-8dd5-9dd06181c6bd/IncomingWebhook/a01017dda5304e609c22b15170b0adbb/e864689d-4721-4807-9618-fed5b5c36541
          # Message title
          title: Pull request Created 
          # Message summary
          summary: Pull request Created 
          # Message text
          text: Pull request Created
